development:
  adapter: mysql2
  reconnect: false
  database: wjt_development
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  reconnect: false
  database: wjt_test
  pool: 5
  username: root
  password: 
  host: localhost
